# Alle hier gesetzten Werte können über `$addon->getProperty($key)` abgefragt werden

package: nv_categorymanager # Pflichtfeld
version: '1.3.0' # Pflichtfeld
author: novinet GmbH & Co KG
supportpage: https://github.com/novinet-git/nv_categorymanager

# Seiten
page:
    title: 'nvCategoryManager' # Werte die mit `translate:` beginnen, werden anhand der Sprachdatei übersetzt. Der Addon-Präfix (hier `demo_addon_`) kann weggelassen werden.
    icon: nv_categorymanager_novinet-icon-logo
    perm: nv_categorymanager[] # Seite ist nur für Admins erreichbar
    pjax: true
    subpages:
        update:
            title: 'Verwaltung'
            icon: rex-icon fa-list
        settings:
            title: translate:nv_categorymanager_settings
            icon: rex-icon fa-cog
        info:
            title: 'Info'
            icon: rex-icon fa-info-circle
            
    
requires:
    redaxo: ^5.5.0
