package: structure_manager
version: '2.0.1'
author: FriendsOfREDAXO
supportpage: https://github.com/friendsofredaxo/structure_manager

page:
    title: translate:structure_manager.title
    icon: rex-icon fa-copy
    perm: admin
    subpages:
        category:
            title: translate:structure_manager.page.category
            icon: rex-icon rex-icon-open-category
        article:
            title: translate:structure_manager.page.article
            icon: rex-icon rex-icon-article
        media_category:
            title: translate:structure_manager.page.media_category
            icon: rex-icon rex-icon-media

requires:
    redaxo: ^5.18.0
    php: ^8.3

conflicts:
    packages:
        nv_categorymanager: '>=0'
        
default_config:
    auto_remove_copy_suffix: true
